### ISSUE TITLE
大佬您好，配置公网IP

### ISSUE THREAD

**Issue by huzhizhao** [AdlerED/LiteFTPD-UNIX#1]
不知如何在服务器如何配置公网IP访问呢？

**Comment by adlered** [comment]
你好，如果你是指LiteFTPD通过公网访问的话，不需要做任何配置，直接远程连接即可。要记得防火墙放行TCP 21端口，如果你用的是云主机的话，要在安全组里放行TCP 21端口！

**Comment by huzhizhao** [comment]
我已在安全组放行21端口，防火墙也已放开21端口。如图
入站规则：
https://s1.ax1x.com/2020/03/14/8MaVS0.png
出站规则：
https://s1.ax1x.com/2020/03/14/8MaeyT.png
是腾讯的主机，CentOS 7.5 64bit

**Comment by adlered** [comment]
问题已解决
